name: kcalc
version: '23.08.5'
grade: stable
base: core22
confinement: strict
adopt-info: kcalc

apps:
  kcalc:
    common-id: org.kde.kcalc.desktop
    command: usr/bin/kcalc
    extensions: [kde-neon]
    plugs:
      - home
      - audio-playback
    environment:
      XCURSOR_SIZE: 24
      XCURSOR_THEME: "Yaru"

slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kcalc.desktop
    bus: session

parts:
  kcalc:
    parse-info: [usr/share/metainfo/org.kde.kcalc.appdata.xml]
    plugin: cmake
    build-packages:
      - libgmp-dev
      - libmpfr-dev
    stage-packages:
      - libgmp10
      - libmpfr6
    source: https://invent.kde.org/utilities/kcalc/-/archive/v23.08.5/kcalc-v23.08.5.tar.gz
    cmake-parameters:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DBUILD_TESTING=OFF"
      - "-DKDE_SKIP_TEST_SETTINGS=ON"
      - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DINSTALL_ICONS=ON"
    override-build: |
      if [ ! -e /usr/share/xml ]
      then ln -s /snap/kf5-*-core22-sdk/current/usr/share/xml/ /usr/share/xml
      fi
      craftctl default
